
 /*
* @Author: jumorzhu@tecent.com
* @Last Modified by:   jumorzhu
* @Created time: 2017-03-10 9:25
*/

 var faker = require('faker');

 module.exports = function () {
        return {
            "messageList": [
                {
                    "id": 559,
                    "type": 1,
                    "detail": "发生的发生的",
                    "username": "为了验证我要起一个超级长超级长的名字，够长了么。。。。",
                    "user_pic": "http://gad.qpic.cn/images/avatar/58539ec487a65.gif",
                    "live_id": 16,
                    "user_id": 38612,
                    "created_at": "2017-03-08 15:40:00",
                    "updated_at": "2017-03-08 15:40:00",
                    "role_type": 2,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 537,
                    "type": 1,
                    "detail": "好怀念",
                    "username": "yingyuaaaaaaa",
                    "user_pic": "http://gad.qpic.cn/images/avatar/58481f3d6c715.gif",
                    "live_id": 16,
                    "user_id": 70238,
                    "created_at": "2017-03-08 10:22:48",
                    "updated_at": "2017-03-08 10:22:48",
                    "role_type": 2,
                    "like_count": 1,
                    "is_liked": false
                },
                {
                    "id": 535,
                    "type": 1,
                    "detail": "人嫩",
                    "username": "薛定谔的猫咪啊哈哈哈哈哈哈哈哈啊哈哈哈哈啊哈哈哈哈哈哈啊哈哈哈哈",
                    "user_pic": "http://gameweb-img.qq.com/gad/20160309/phpCVrmt7.1457509018.85x85.1457509031.jpg",
                    "live_id": 16,
                    "user_id": 77038,
                    "created_at": "2017-03-08 10:21:15",
                    "updated_at": "2017-03-08 10:21:15",
                    "role_type": 2,
                    "like_count": 1,
                    "is_liked": false
                },
                {
                    "id": 534,
                    "type": 1,
                    "detail": "啊",
                    "username": "yingyuaaaaaaa",
                    "user_pic": "http://gad.qpic.cn/images/avatar/58481f3d6c715.gif",
                    "live_id": 17,
                    "user_id": 70238,
                    "created_at": "2017-03-08 10:21:08",
                    "updated_at": "2017-03-08 10:21:08",
                    "role_type": 2,
                    "like_count": 1,
                    "is_liked": false
                },
                {
                    "id": 533,
                    "type": 2,
                    "detail": "http://gameweb-img.qq.com/gad/20170308/ywYuycrFyZ2IYC6wYZ6E6WzcgtsdXEhH8x2XnYNgxfEa5941FmrS64EW1XaneAy.1488939384.jpg",
                    "username": "12",
                    "user_pic": "http://wx.qlogo.cn/mmopen/lLib7UklNhwDgIw8NeHqhpm3qE8sXIYcibRZaGOuHWgwQJFyUkwibupfUnC6Xz1EpIlHG2kyBPFZic6g3QHruouDFu02OQ4zjrnP/0",
                    "live_id": 20,
                    "user_id": 151584,
                    "created_at": "2017-03-08 10:16:41",
                    "updated_at": "2017-03-08 10:16:41",
                    "role_type": 1,
                    "like_count": 2,
                    "is_liked": false
                },
                {
                    "id": 532,
                    "type": 2,
                    "detail": "http://gameweb-img.qq.com/gad/20170308/jRqmavKqyHEyOiX3SPbEByHZ0i30elnlucEAvnksKEtQZQcZloGXR5rpTegc3mrP.1488939370.jpg",
                    "username": "12",
                    "user_pic": "http://wx.qlogo.cn/mmopen/lLib7UklNhwDgIw8NeHqhpm3qE8sXIYcibRZaGOuHWgwQJFyUkwibupfUnC6Xz1EpIlHG2kyBPFZic6g3QHruouDFu02OQ4zjrnP/0",
                    "live_id": 20,
                    "user_id": 151584,
                    "created_at": "2017-03-08 10:16:27",
                    "updated_at": "2017-03-08 10:16:27",
                    "role_type": 1,
                    "like_count": 2,
                    "is_liked": false
                },
                {
                    "id": 531,
                    "type": 3,
                    "detail": "http://file.gad.qq.com/attachment/audio?audio_id=1091_b3ecbcfcad614f4dad2888c39cc5e532&duration=8683",
                    "username": "12",
                    "user_pic": "http://wx.qlogo.cn/mmopen/lLib7UklNhwDgIw8NeHqhpm3qE8sXIYcibRZaGOuHWgwQJFyUkwibupfUnC6Xz1EpIlHG2kyBPFZic6g3QHruouDFu02OQ4zjrnP/0",
                    "live_id": 20,
                    "user_id": 151584,
                    "created_at": "2017-03-08 10:15:59",
                    "updated_at": "2017-03-08 10:15:59",
                    "role_type": 1,
                    "like_count": 1,
                    "is_liked": false
                },
                {
                    "id": 530,
                    "type": 1,
                    "detail": "111111",
                    "username": "乌拉拉",
                    "user_pic": "http://gameweb-img.qq.com/gad/20151106/php4KChkT.1446791786.85x85.1446791794.jpg",
                    "live_id": 17,
                    "user_id": 76753,
                    "created_at": "2017-03-08 10:15:48",
                    "updated_at": "2017-03-08 10:15:48",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 529,
                    "type": 1,
                    "detail": "hh",
                    "username": "12",
                    "user_pic": "http://wx.qlogo.cn/mmopen/lLib7UklNhwDgIw8NeHqhpm3qE8sXIYcibRZaGOuHWgwQJFyUkwibupfUnC6Xz1EpIlHG2kyBPFZic6g3QHruouDFu02OQ4zjrnP/0",
                    "live_id": 20,
                    "user_id": 151584,
                    "created_at": "2017-03-08 10:15:11",
                    "updated_at": "2017-03-08 10:15:11",
                    "role_type": 1,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 528,
                    "type": 1,
                    "detail": "11",
                    "username": "薛定谔的猫咪啊哈哈哈哈哈哈哈哈啊哈哈哈哈啊哈哈哈哈哈哈啊哈哈哈哈",
                    "user_pic": "http://gameweb-img.qq.com/gad/20160309/phpCVrmt7.1457509018.85x85.1457509031.jpg",
                    "live_id": 20,
                    "user_id": 77038,
                    "created_at": "2017-03-08 10:14:38",
                    "updated_at": "2017-03-08 10:14:38",
                    "role_type": 2,
                    "like_count": 1,
                    "is_liked": false
                },
                {
                    "id": 527,
                    "type": 1,
                    "detail": "好厉害",
                    "username": "12",
                    "user_pic": "http://wx.qlogo.cn/mmopen/lLib7UklNhwDgIw8NeHqhpm3qE8sXIYcibRZaGOuHWgwQJFyUkwibupfUnC6Xz1EpIlHG2kyBPFZic6g3QHruouDFu02OQ4zjrnP/0",
                    "live_id": 20,
                    "user_id": 151584,
                    "created_at": "2017-03-08 10:13:27",
                    "updated_at": "2017-03-08 10:13:27",
                    "role_type": 1,
                    "like_count": 1,
                    "is_liked": false
                },
                {
                    "id": 526,
                    "type": 1,
                    "detail": "1111\n",
                    "username": "乌拉拉",
                    "user_pic": "http://gameweb-img.qq.com/gad/20151106/php4KChkT.1446791786.85x85.1446791794.jpg",
                    "live_id": 17,
                    "user_id": 76753,
                    "created_at": "2017-03-08 10:08:34",
                    "updated_at": "2017-03-08 10:08:34",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 525,
                    "type": 1,
                    "detail": "# This file contains the mappings of IP addresses to host names. Each\n# entry should be kept on an individual line. The IP address should\n# be placed in the first column followed by the corresponding host name.\n# The IP address and the host name should be separated by at least one",
                    "username": "刘森",
                    "user_pic": "http://wx.qlogo.cn/mmopen/zOxuVCyFiaGTOJyj1JO6sfmItjQ7YvqbYITMSC9x12nGHqqmiawyBOg9VNjZzY4BCpibNJvHUBnzKb6IKYhGYic14dVhaFBNz7eK/0",
                    "live_id": 20,
                    "user_id": 151566,
                    "created_at": "2017-03-07 19:49:59",
                    "updated_at": "2017-03-07 19:49:59",
                    "role_type": 3,
                    "like_count": 1,
                    "is_liked": false
                },
                {
                    "id": 524,
                    "type": 1,
                    "detail": "特",
                    "username": "刘森",
                    "user_pic": "http://wx.qlogo.cn/mmopen/zOxuVCyFiaGTOJyj1JO6sfmItjQ7YvqbYITMSC9x12nGHqqmiawyBOg9VNjZzY4BCpibNJvHUBnzKb6IKYhGYic14dVhaFBNz7eK/0",
                    "live_id": 20,
                    "user_id": 151566,
                    "created_at": "2017-03-07 19:48:55",
                    "updated_at": "2017-03-07 19:48:55",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 523,
                    "type": 1,
                    "detail": "方法",
                    "username": "刘森",
                    "user_pic": "http://wx.qlogo.cn/mmopen/zOxuVCyFiaGTOJyj1JO6sfmItjQ7YvqbYITMSC9x12nGHqqmiawyBOg9VNjZzY4BCpibNJvHUBnzKb6IKYhGYic14dVhaFBNz7eK/0",
                    "live_id": 20,
                    "user_id": 151566,
                    "created_at": "2017-03-07 19:48:10",
                    "updated_at": "2017-03-07 19:48:10",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 522,
                    "type": 1,
                    "detail": "防撒旦",
                    "username": "刘森",
                    "user_pic": "http://wx.qlogo.cn/mmopen/zOxuVCyFiaGTOJyj1JO6sfmItjQ7YvqbYITMSC9x12nGHqqmiawyBOg9VNjZzY4BCpibNJvHUBnzKb6IKYhGYic14dVhaFBNz7eK/0",
                    "live_id": 20,
                    "user_id": 151566,
                    "created_at": "2017-03-07 19:48:07",
                    "updated_at": "2017-03-07 19:48:07",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 521,
                    "type": 1,
                    "detail": "特殊他",
                    "username": "刘森",
                    "user_pic": "http://wx.qlogo.cn/mmopen/zOxuVCyFiaGTOJyj1JO6sfmItjQ7YvqbYITMSC9x12nGHqqmiawyBOg9VNjZzY4BCpibNJvHUBnzKb6IKYhGYic14dVhaFBNz7eK/0",
                    "live_id": 20,
                    "user_id": 151566,
                    "created_at": "2017-03-07 19:48:04",
                    "updated_at": "2017-03-07 19:48:04",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 520,
                    "type": 1,
                    "detail": "苏打粉",
                    "username": "为了验证我要起一个超级长超级长的名字，够长了么。。。。",
                    "user_pic": "http://gad.qpic.cn/images/avatar/58539ec487a65.gif",
                    "live_id": 19,
                    "user_id": 38612,
                    "created_at": "2017-03-07 19:43:28",
                    "updated_at": "2017-03-07 19:43:28",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 519,
                    "type": 1,
                    "detail": "发生大幅",
                    "username": "为了验证我要起一个超级长超级长的名字，够长了么。。。。",
                    "user_pic": "http://gad.qpic.cn/images/avatar/58539ec487a65.gif",
                    "live_id": 19,
                    "user_id": 38612,
                    "created_at": "2017-03-07 19:41:58",
                    "updated_at": "2017-03-07 19:41:58",
                    "role_type": 3,
                    "like_count": 0,
                    "is_liked": false
                },
                {
                    "id": 518,
                    "type": 1,
                    "detail": "萨芬的",
                    "username": "为了验证我要起一个超级长超级长的名字，够长了么。。。。",
                    "user_pic": "http://gad.qpic.cn/images/avatar/58539ec487a65.gif",
                    "live_id": 20,
                    "user_id": 38612,
                    "created_at": "2017-03-07 19:11:50",
                    "updated_at": "2017-03-07 19:11:50",
                    "role_type": 2,
                    "like_count": 0,
                    "is_liked": false
                }
            ],
            "total": 40,
            "code": 0
        }
 }